### ISSUE TITLE
join forces?

### ISSUE THREAD

**Issue by tischi** [henrypinkard/IMSWriter#1]
Hi!

I just wanted to let you that I also wrote java code for writing Imaris:
https://github.com/tischi/fiji-plugin-bigDataTools/blob/master/src/main/java/bigDataTools/Hdf55ImarisBdvWriter.java

Maybe good to know in case either of us is going to invest more time into this.

**Comment by henrypinkard** [comment]
Hi Christian, good to know--thanks for reaching out. 

Doubtful that I will put any more time into this though. I completed it several years ago and have been using it without issue since

**Comment by rmd13** [comment]
Hi Christian, 
That's really a great work for fiji!
Can the .jar files for that fiji projec also be loaded into matlab via javaaddpath and then call functions to make imaris files from matlab?I have tried but it cannot be loaded, or the object cannot be created, or function is unknown. Do you have any suggestions?
Thanks.

**Comment by rmd13** [comment]
Hi, I find the following lines from mathwork forum
it is worth mentioning that if your class is under a package you should create the instance as: myHelloObject = mypackage.HelloWorld
This may be the reason why I cannot,create an object

**Comment by tischi** [comment]
Thanks! Unfortunately I have no clue about using java in MATLAB!
Did you figure it out?

**Comment by rmd13** [comment]
hi tischi,
Could u re-compile the jar file using java 7？ matlab only works with java7, and I am new to java.
Thanks in advance.

**Comment by henrypinkard** [comment]
@rmd06 @tischi  FYI, I wrote a python wrapper for this library to make it more accessible
