### ISSUE TITLE
How to run in matlab?

### ISSUE THREAD

**Issue by rmd13** [henrypinkard/IMSWriter#2]

**Comment by rmd13** [comment]
I run the code in matlab following python example:

javaaddpath D:\QMDownload\3\IMSWriter-master\lib\ImarisWriter.jar
javaaddpath D:\QMDownload\3\IMSWriter-master\lib\jhdf5.jar
javaaddpath D:\QMDownload\3\IMSWriter-master\lib\jhdf5obj.jar
javaaddpath D:\QMDownload\3\IMSWriter-master\lib\jhdfobj.jar

dir = 'D:\QMDownload\3';
name = 'filename_prefix';
shape = [1024, 1024, 12];
byte_depth = 2;
num_channels = 2;
num_frames = 3;
pixel_size_xy_um = 0.5;
pixel_size_z_um = 1.0;
%open writer
writer = imariswriter.ImarisJavaWrapper(dir, name, shape, byte_depth, num_channels, num_frames, pixel_size_xy_um, pixel_size_z_um)

Matlab says that:
Undefined variable "imariswriter" or class "imariswriter.ImarisJavaWrapper".

**Comment by rmd13** [comment]
Sorry, I didnot notice it is a python script.

I run the python version in cmd and get the following:
D:\QMDownload\3\IMSWriter-master>python example.py
Traceback (most recent call last):
  File "example.py", line 23, in <module>
    writer.write_z_slice(tile, z_index, channel_index, time_index, elapsed_time_
ms)
TypeError: __exit__() takes exactly 1 argument (4 given)

**Comment by rmd13** [comment]
After adjusting the code, finally I can run the example.py in python 2 by calling:

python exmaple.py

but there is a recurring java message box pop up:

java.lang.classcastexception java.lang.string cannot be cast to [S...?( I cannot see the words after here because this part is out of dialogue box)
at main.java.HDFPreprocessor.process(HDFPreprocessor.java.40)
at main.java.ImarisWriter $1.run(ImarisWriter.java:48)
at java.util.concurrent.Executors$Runnable adaptors.call(unknown source)
at java.util.concurrent.FeatureTask.tun(unknown source)
at java.util.concurrent.TjreadPoolEcecutor.runworker(unknown source)
at java.util.concurrent.TjreadPoolEcecutor.$worker.run(unknown source)
at java.lang.thread.run(unknown source)

**Comment by rmd13** [comment]
In the ImarisWriter.class line 140:
      PipelineImage pi = ImarisWriter.this.preprocessor_.process(batch);
this calls the HDFPreprocessor.class:
      public PipelineImage process(LinkedList<PipelineImage> slices)
        ...
        for (short s : (short[])((PipelineImage)slices.get(i)).pixels) (line 48)

It seems that PipelineImage)slices.get(i)).pixels is a string, but use here as a short, sp the cast failed.

This may arise from my modification in exmaple.py
line 20:
	original line is :
		tile = rand.randint(0, 4096, shape[2], dtype=np.uint16)
	 my version is:
		tile = rand.randint(12, 34, 56)

I have to modify this line becuase if I use the original line, python cast the error:
Traceback (most recent call last):
  File "example.py", line 21, in <module>
    tile = rand.randint(0, 4096, shape[2], dtype=np.uint16)
  File "mtrand.pyx", line 875, in mtrand.RandomState.randint (numpy\random\mtran
d\mtrand.c:10248)
TypeError: randint() got an unexpected keyword argument 'dtype'

**Comment by rmd13** [comment]
I also have to change the number 
from 
	tile = rand.randint(12, 4096, 1024)
to
	tile = rand.randint(12, 34, 56)
because if I use (12, 4096, 1024), error appears:

D:\QMDownload\3\IMSWriter-master>python example.py
Traceback (most recent call last):
  File "example.py", line 24, in <module>
    writer.write_z_slice(tile, z_index, channel_index, time_index, elapsed_time_
ms)
  File "D:\QMDownload\3\IMSWriter-master\imariswriter.py", line 53, in write_z_s
lice
    self.writer.addImage(pixels.tobytes(), slice, channel, frame, timestamp)
  File "D:\QMDownload\3\IMSWriter-master\py4j\java_gateway.py", line 1248, in __
call__
    args_command, temp_args = self._build_args(*args)
  File "D:\QMDownload\3\IMSWriter-master\py4j\java_gateway.py", line 1218, in _b
uild_args
    [get_command_part(arg, self.pool) for arg in new_args])
  File "D:\QMDownload\3\IMSWriter-master\py4j\protocol.py", line 292, in get_com
mand_part
    command_part = STRING_TYPE + escape_new_line(parameter)
  File "D:\QMDownload\3\IMSWriter-master\py4j\protocol.py", line 187, in escape_
new_line
    return smart_decode(original).replace("\\", "\\\\").\
  File "D:\QMDownload\3\IMSWriter-master\py4j\protocol.py", line 219, in smart_d
ecode
    return unicode(s, "utf-8")
UnicodeDecodeError: 'utf8' codec can't decode byte 0xef in position 8: invalid c
ontinuation byte

=======
I tried several different number and found that (12, 34, 56) can skip this error,but then that java exception dialogue pop up.


Also, I have to delete the fourth argument because of error:
Traceback (most recent call last):
  File "example.py", line 21, in <module>
    tile = rand.randint(0, 4096, shape[2], np.uint16)
  File "mtrand.pyx", line 875, in mtrand.RandomState.randint (numpy\random\mtran
d\mtrand.c:10265)
TypeError: randint() takes at most 3 positional arguments (4 given)

**Comment by henrypinkard** [comment]
This is a python 3 script (tested in 3.6). Not sure what will happen in any earlier versions

**Comment by rmd13** [comment]
I have installed python 3.7 and the numpy for 3.7(numpy-1.15.0-cp37-none-win_amd64.whl)

When I run I got the error:
=======
D:\QMDownload\3\IMSWriter-master>python example.py
Traceback (most recent call last):
  File "example.py", line 14, in <module>
    with ImarisJavaWrapper(dir, name, shape, byte_depth, num_channels, num_frame
s, pixel_size_xy_um, pixel_size_z_um) as writer:
  File "D:\QMDownload\3\IMSWriter-master\imariswriter.py", line 29, in __init__
    javaopts=['-Xmx4096m', '-Djava.library.path='+lib_path], die_on_exit=True)
  File "D:\QMDownload\3\IMSWriter-master\py4j\java_gateway.py", line 2087, in la
unch_gateway
    enable_auth=enable_auth)
  File "D:\QMDownload\3\IMSWriter-master\py4j\java_gateway.py", line 330, in lau
nch_gateway
    _port = int(proc.stdout.readline())
ValueError: invalid literal for int() with base 10: b''
=======

Is this a problem of py4j? I installed py4j-0.10.7.
Thanks.

**Comment by henrypinkard** [comment]
Yes that looks like its coming from py4j. Maybe try playing with your java version and making sure you can start up py4j on its own first

**Comment by rmd13** [comment]
I try to run py4j on its own following guide:

C:\Users\rmd>python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD6
4)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from py4j.java_gateway import JavaGateway
>>> gateway = JavaGateway()
>>> random = gateway.jvm.java.util.Random()
Traceback (most recent call last):
  File "C:\Users\rmd\AppData\Local\Programs\Python\Python37\lib\site-packages\py
4j\java_gateway.py", line 931, in _get_connection
    connection = self.deque.pop()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rmd\AppData\Local\Programs\Python\Python37\lib\site-packages\py
4j\java_gateway.py", line 1069, in start
    self.socket.connect((self.address, self.port))
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rmd\AppData\Local\Programs\Python\Python37\lib\site-packages\py
4j\java_gateway.py", line 1651, in __getattr__
    "\n" + proto.END_COMMAND_PART)
  File "C:\Users\rmd\AppData\Local\Programs\Python\Python37\lib\site-packages\py
4j\java_gateway.py", line 985, in send_command
    connection = self._get_connection()
  File "C:\Users\rmd\AppData\Local\Programs\Python\Python37\lib\site-packages\py
4j\java_gateway.py", line 933, in _get_connection
    connection = self._create_connection()
  File "C:\Users\rmd\AppData\Local\Programs\Python\Python37\lib\site-packages\py
4j\java_gateway.py", line 939, in _create_connection
    connection.start()
  File "C:\Users\rmd\AppData\Local\Programs\Python\Python37\lib\site-packages\py
4j\java_gateway.py", line 1081, in start
    raise Py4JNetworkError(msg, e)
py4j.protocol.Py4JNetworkError: An error occurred while trying to connect to the
 Java server (127.0.0.1:25333)
>>>

**Comment by rmd13** [comment]
The python wrapper imariswriter.py seems to enable python to use java.

I'm wondering if the IMSWriter could be run from Matlab instead of python?

More than 1 year ago you wrote some demo code in matlab. At that time because I cannot run smoothly because of .jar shortage.
Now this work has include all jar packages, so can this IMSWriter run from Matlab using that demo code? or the IMSWriter has been updated this time so that it only could be run from python?

Because matlab can run java natively, so there is no need of such as py4j package and numpy. 

I have tried to load all these jars to javaclasspath, but I cannot initiate an object of ImarisWriter:

javaaddpath D:\QMDownload\3\IMSWriter-master\lib\ImarisWriter.jar
javaaddpath D:\QMDownload\3\IMSWriter-master\lib\jhdf5.jar
javaaddpath D:\QMDownload\3\IMSWriter-master\lib\jhdf5obj.jar
javaaddpath D:\QMDownload\3\IMSWriter-master\lib\jhdfobj.jar
writer = ImarisWriter();

Error:
Undefined function or variable 'ImarisWriter'.

Could you help me on this.Thanks.

**Comment by rmd13** [comment]
Here is my example:

javaaddpath D:\QMDownload\3\IMSWriter-master\lib\ImarisWriter.jar
javaaddpath D:\QMDownload\3\IMSWriter-master\lib\jhdf5.jar
javaaddpath D:\QMDownload\3\IMSWriter-master\lib\jhdf5obj.jar
javaaddpath D:\QMDownload\3\IMSWriter-master\lib\jhdfobj.jar

dir = tempdir;
name = 'filename_prefix';
shape = [1024, 1024, 12];
byte_depth = 2;
num_channels = 2;
num_frames = 3;
pixel_size_xy = 0.5;
pixel_size_z = 1.0;

writer = ImarisWriter(dir,name,shape(1),shape(2),byte_depth,shape(3),num_channels,num_frames,pixel_size_xy,pixel_size_z);
for time_index = 1 :  num_frames
    for channel_index = 1 :  num_channels
        for z_index = 1 :  shape(3)
            tile = uint16(4096*rand(1,shape(1)*shape(2)));
            elapsed_time_ms = time_index * 10000;
            % here the tile need to be converted to byte? 
                % as seen from python's version class: self.writer.addImage(pixels.tobytes()...
            writer.addImage(tile, z_index, channel_index, time_index, elapsed_time_ms)
        end
    end
end



Undefined function or variable 'ImarisWriter'.

Error in Untitled (line 15)
writer =
ImarisWriter(dir,name,shape(1),shape(2),byte_depth,shape(3),num_channels,num_frames,pixel_size_xy,pixel_size_z);

**Comment by rmd13** [comment]
I have download all the other jar file from
 https://support.hdfgroup.org/ftp/HDF5/prev-releases/HDF-JAVA/HDF-JAVA-2.7/bin/win64/hdf-java/lib/
and also add them to matlab, but problem still the same:

javaaddpath D:\QMDownload\3\IMSWriter-master\lib\jhdf.jar
javaaddpath D:\QMDownload\3\IMSWriter-master\lib\jhdf4obj.jar
javaaddpath D:\QMDownload\3\IMSWriter-master\lib\jhdf5.jar
javaaddpath D:\QMDownload\3\IMSWriter-master\lib\jhdf5obj.jar
javaaddpath D:\QMDownload\3\IMSWriter-master\lib\jhdfobj.jar
javaaddpath D:\QMDownload\3\IMSWriter-master\lib\jhdfview.jar
javaaddpath D:\QMDownload\3\IMSWriter-master\lib\junit.jar
javaaddpath D:\QMDownload\3\IMSWriter-master\lib\nc2obj.jar
javaaddpath D:\QMDownload\3\IMSWriter-master\lib\netcdf.jar
javaaddpath D:\QMDownload\3\IMSWriter-master\lib\fits.jar
javaaddpath D:\QMDownload\3\IMSWriter-master\lib\fitsobj.jar
javaaddpath D:\QMDownload\3\IMSWriter-master\lib\ImarisWriter.jar
java.lang.System.load('D:\QMDownload\3\IMSWriter-master\lib\jhdf5.dll');
java.lang.System.load('D:\QMDownload\3\IMSWriter-master\lib\jhdf.dll');

dir = tempdir;
name = 'filename_prefix';
shape = [1024, 1024, 12];
byte_depth = 2;
num_channels = 2;
num_frames = 3;
pixel_size_xy = 0.5;
pixel_size_z = 1.0;

writer = ImarisWriter(dir,name,shape(1),shape(2),byte_depth,shape(3),num_channels,num_frames,pixel_size_xy,pixel_size_z);

Undefined function or variable 'ImarisWriter'.

Error in Untitled (line 57)
writer = ImarisWriter(dir,name,shape(1),shape(2),byte_depth,shape(3),num_channels,num_frames,pixel_size_xy,pixel_size_z);

**Comment by henrypinkard** [comment]
In principle it works in Matlab, but I don't use Matlab anymore, so for setting it up it works. You should be able to get in working in Python. I wrote the wrapper only a couple months ago. I don't have time to help you debug and get it working, but if you do figure something out it would be great to file a pull request and contribute to this repository so others can benefit from it.

**Comment by rmd13** [comment]
Finally I made it by another way: I use the matlab-embedded HDF5 library functions to make ims file from scratch. It's really cool.
Anyway, thank you again for the IMSwriter to enlighten me to make imaris file generation from scratch.
